#!/bin/bash
# Stop hook — auto-commit my-ai-agents snapshot when Claude/ changes.
# Mirror-only, no push. Commit message is generated by `claude --print --bare`
# from the actual diff so it reflects intent, not a generic "auto-sync" stamp.
# If message generation fails or doesn't match conventional-commits, the hook
# un-stages and exits 0 — leaving the work for the user to commit manually.

set -uo pipefail

# Recursion guard — this script calls `claude --print` to generate a commit
# message; that child claude session also fires its Stop hook, which would
# re-enter this script. Set an env-var sentinel so the recursive invocation
# bails out immediately. Without this, fork-bomb / git-lock contention.
[ -n "${CLAUDE_AUTOCOMMIT_RUNNING:-}" ] && exit 0
export CLAUDE_AUTOCOMMIT_RUNNING=1

# Path resolution. Defaults assume ~/Repos/my-ai-agents; override per-device by
# creating ~/.claude/.sync-config with: SNAPSHOT_REPO="/your/path/to/my-ai-agents"
CLAUDE_DIR="$HOME/.claude"
SNAPSHOT_REPO="$HOME/Repos/my-ai-agents"
[ -f "$CLAUDE_DIR/.sync-config" ] && . "$CLAUDE_DIR/.sync-config"
LOG="$CLAUDE_DIR/sync-to-snapshot.log"

cd "$SNAPSHOT_REPO" 2>/dev/null || exit 0

# Skip mid-operation states
{ [ -d .git/rebase-merge ] || [ -d .git/rebase-apply ] || \
  [ -f .git/MERGE_HEAD ] || [ -f .git/CHERRY_PICK_HEAD ]; } && {
  printf '%s [SKIP] mid-operation\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG"
  exit 0
}

# Skip on detached HEAD
git symbolic-ref -q HEAD >/dev/null || {
  printf '%s [SKIP] detached HEAD\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG"
  exit 0
}

# Skip if user already has something staged (might be writing their own commit)
[ -n "$(git diff --cached --name-only)" ] && {
  printf '%s [SKIP] user has staged changes\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG"
  exit 0
}

# Drift sweep: mirror every whitelisted live file into snapshot to catch
# changes that bypassed the PostToolUse Edit|Write hook (harness permission
# updates writing settings.local.json directly, manual edits outside Claude,
# etc.). Reuses sync-to-snapshot.sh so whitelist + secret guard stay single-
# sourced.
{
  for f in CLAUDE.md settings.json statusline.sh; do
    [ -f "$CLAUDE_DIR/$f" ] && printf '%s\n' "$CLAUDE_DIR/$f"
  done
  [ -d "$CLAUDE_DIR/scripts" ] && find "$CLAUDE_DIR/scripts" -type f
  [ -d "$CLAUDE_DIR/agents" ]  && find "$CLAUDE_DIR/agents"  -type f
  [ -d "$CLAUDE_DIR/skills" ]  && find "$CLAUDE_DIR/skills"  -type f
  [ -d "$CLAUDE_DIR/rules" ]   && find "$CLAUDE_DIR/rules"   -type f
} | while IFS= read -r f; do
  printf '{"tool_name":"Edit","tool_input":{"file_path":"%s"}}' "$f" \
    | bash "$CLAUDE_DIR/scripts/sync-to-snapshot.sh"
done

# skills/synced/ is claude.ai-managed and changes every session; it is not
# carried in the snapshot. Drop it if an older sweep copied it in.
#
# Deliberately NOT a general "delete what is gone live" mirror: on a device that
# has just pulled but not yet run bootstrap, the newly pulled files are missing
# live, and such a sweep would delete and auto-commit them. Live deletions are
# propagated by hand — sync-device's verification step lists them.
rm -rf Claude/skills/synced

# Nothing to commit under Claude/ after sweep → silent no-op
[ -z "$(git status --porcelain Claude/)" ] && exit 0

git add Claude/

DIFFSTAT=$(git diff --cached --stat -- Claude/)
DIFFBODY=$(git diff --cached -- Claude/ | head -300)
RECENT=$(git log -5 --format='%s' -- Claude/)

PROMPT=$(cat <<EOF
Generate one conventional-commits message for the staged diff below in $SNAPSHOT_REPO.

Recent commit style from this repo (match this voice):
$RECENT

Format rules:
- Single line, <70 chars when possible
- <type>(<scope>): <lowercase description>
- Types: feat, fix, refactor, docs, chore, style, test, build, perf, ci, security
- Imperative mood, no trailing period
- Scope examples used here: hooks, scripts, settings, skills, agents, setup
- Output ONLY the message line — no quotes, no preamble, no markdown

Stat:
$DIFFSTAT

Diff (truncated to 300 lines):
$DIFFBODY
EOF
)

MSG=$(printf '%s' "$PROMPT" | claude --print --no-session-persistence --model haiku 2>>"$LOG" \
  | head -1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr -d '`"')

# Validate: must be a conventional-commits line, not a generic "auto-sync"
if [ -z "$MSG" ] || \
   ! echo "$MSG" | grep -qE '^(feat|fix|refactor|docs|chore|style|test|build|revert|perf|ci|security)(\([a-z0-9_-]+\))?: [a-z]' || \
   echo "$MSG" | grep -qE 'auto-sync'; then
  printf '%s [ABORT] message did not pass validation: %s — un-staged, leaving for manual commit\n' \
    "$(date '+%Y-%m-%d %H:%M:%S')" "$MSG" >> "$LOG"
  git reset -q HEAD -- Claude/ 2>/dev/null
  exit 0
fi

# Overlapping Stop runs (turns ending seconds apart, or two sessions) each stage
# the same sweep; whichever commits first empties the index for the others.
git diff --cached --quiet -- Claude/ && exit 0

if git commit -q -m "$MSG" >>"$LOG" 2>&1; then
  SHA=$(git rev-parse --short HEAD)
  printf '%s [COMMIT] %s — %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$SHA" "$MSG" >> "$LOG"
else
  printf '%s [FAIL] git commit failed\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG"
fi
exit 0
